var tasks = {};
tasks["Elena"]={};
tasks["Rachael"]={};
tasks["Ben"]={};
tasks["Hanna"]={};
tasks["Elena"].Monday=[
  "Take Accesment Test","<img src='AugustPreaccess1.jpg' width='75'>","<img src='AugustPreaccess2.jpg' width='75'>","<img src='AugustPreaccess3.jpg' width='75'>","<img src='AugustPreaccess4.jpg' width='75'>","<img src='AugustPreaccess5.jpg' width='75'>"
];
tasks["Elena"].Tueday=[
  "sopmem","sopmem","sopmem","sopmem","sopmem"
];
tasks["Elena"].Wednesday=[
  "sopmem","sopmem","sopmem","sopmem","sopmem"
];
tasks["Elena"].Thursday=[
  "sopmem","sopmem","sopmem","sopmem","sopmem"
];
tasks["Elena"].Friday=[
  "sopmem","sopmem","sopmem","sopmem","sopmem"
];
tasks["Rachael"].Monday=[
  "asdfasdf","asdfasdf","asdfasdf","asdfasdf","asdfasdf"
];
tasks["Rachael"].Tuesday=[
  "asdfasdf","asdfasdf","asdfasdf","asdfasdf","asdfasdf"
];
tasks["Rachael"].Wednesday=[
  "asdfasdf","asdfasdf","asdfasdf","asdfasdf","asdfasdf"
];
tasks["Rachael"].Thursday=[
  "asdfasdf","asdfasdf","asdfasdf","asdfasdf","asdfasdf"
];
tasks["Rachael"].Friday=[
  "asdfasdf","asdfasdf","asdfasdf","asdfasdf","asdfasdf"
];
tasks["Ben"].Monday=[
  "allkjf","allkjf","allkjf","allkjf","allkjf"
];
tasks["Ben"].Tuesday=[
  "allkjf","allkjf","allkjf","allkjf","allkjf"
];
tasks["Ben"].Wednesday=[
  "allkjf","allkjf","allkjf","allkjf","allkjf"
];
tasks["Ben"].Thursday=[
  "allkjf","allkjf","allkjf","allkjf","allkjf"
];
tasks["Ben"].Friday=[
  "allkjf","allkjf","allkjf","allkjf","allkjf"
];
tasks["Hanna"].Monday=[
  "llkj","llkj","llkj","llkj","llkj",
];
tasks["Hanna"].Tuesday=[
  "llkj","llkj","llkj","llkj","llkj",
];
tasks["Hanna"].Wednesday=[
  "llkj","llkj","llkj","llkj","llkj",
];
tasks["Hanna"].Thursday=[
  "llkj","llkj","llkj","llkj","llkj",
];
tasks["Hanna"].Friday=[
  "llkj","llkj","llkj","llkj","llkj",
];
