var historicalEvents = ["University of Bologna",
    "Leader: Stalin",
    "Explorer: Christopher Columbus",
    "Explorer: Magellan",
    "War: Korean War",
    "Fall of Berlin Wall",
    "Scientist: Darwin",
    "Invention: X-ray",
    "War: September 11th",
    "Rise of Aztecs",
    "Writer: Maya Angelou",
    "Invention: Iron Age",
    "Angkor Wat",
    "War: Chinese Revolution",
    "War: Battle of Thermopylae",
    "Writer: Marx",
    "Sputnik",
    "War: Battle of Vienna",
    "Invention: Gunpowder",
    "Black Death",
    "Womans Suffrage",
    "Invention: Railroad",
    "War: Russian Revolution",
    "Scientist: Pasteur",
    "Leader: Charlemagne",
    "Explorer: Hudson",
    "Great Pyramid",
    "War: Spanish Armada",
    "Kamakura Shogunate",
    "Invention: Vaccine",
    "Space Race",
    "Rise of Inca",
    "Scientist: Lovelace",
    "Invention: Telephone",
    "Leader: Alexander the Great",
    "Leader: Muhammad",
    "Moon Landing",
    "Invention: Steam Engine",
    "Leader: Elizabeth I",
    "War: Gulf War 1",
    "War: First Crusade",
    "Leader: Hitler",
    "Leader: Buddha",
    "Writer: Twain",
    "Invention: ether anesthetic",
    "Invention: Atomic Bomb",
    "Leader: Mao",
    "Leader: Lenin",
    "Explorer: Cooke",
    "Renaissance",
    "War: End of Apartheid",
    "Writer: Mary Shelley",
    "Invention: Birth Control",
    "Leader: Confucius",
    "Explorer: Jamestown",
    "Abolitionist Movement",
    "Leader: Suleiman the Magnificent",
    "Rise of Greece",
    "War: Norman Conquest of England",
    "League of Nations",
    "Explorer: Armstrong",
    "Writer: Hans Christian Andersen",
    "Scientist: GW Carver",
    "War: American Civil War",
    "Leader: JFK",
    "Code of Hammurabi",
    "Writer: Lewis Carol",
    "Invention: Movable Type",
    "Leader: Genghis Khan",
    "Scientist: Jane Goodall",
    "Suez Canal",
    "Leader: Qin",
    "Boston Tea Party",
    "Invention: Bronze Age",
    "War: Vietnam War",
    "War: French Revolution",
    "War: Spanish Independence",
    "Leader: Jesus",
    "War: Battle of Tours",
    "Invention: Powered flight",
    "Invention: Steam Boat",
    "Invention: Agriculture",
    "War: World War I",
    "War: Cortes Conquers Aztecs",
    "Explorer: Marco Polo",
    "War: Spanish-American War",
    "War: Gulf War 2",
    "War: Turks take Constantinople",
    "War: Russo-Japanese War",
    "Fall of Rome",
    "War: Pizarro Conquers Inca",
    "Julian Calendar",
    "Invention: Internet",
    "Writer: Dickens",
    "Explorer: Buzz Aldrin",
    "Taj Mahal",
    "War: World War II",
    "War: Battle of Marathon",
    "Writer: Victor Hugo",
    "War: US Civil Rights Movement",
    "Invention: Penicillin",
    "Scientist: Galileo",
    "War: Greco-Persian War",
    "Invention: Telegraph",
    "Invention: Cities",
    "Writer: Shakespeare",
    "Leader: Martin Luther",
    "Writer: Bronte Sisters",
    "Invention: Wheeled Vehicles",
    "War: Six-Day War",
    "Spanish Flu",
    "Roman Republic",
    "African Colonization",
    "Invention: Stone Age",
    "War: Cuban Missile Crisis",
    "Great Wall",
    "Invention: Writing",
    "United Nations",
    "Scientist: Tesla",
    "Magna Charta",
    "War: Indian Independence",
    "Scientist: Newton",
    "Scientist: Copernicus",
    "War: American Revolution",
    "Invention: Spinning Jenny",
    "Explorer: Yuri Gagarin",
    "War: Pearl Harbor",
    "Great Depression",
    "War: Haitian Independence",
    "Scientist: Flemming",
    "War: English Civil War",
    "Roman Empire",
    "Explorer: Leif Erickson",
    "Industrial Revolution",
    "War: D-Day Landings",
    "Scientist: Watson & Crick",
    "Scientist: Marie Curie",
    "Columbian Exchange",
    "Invention: Radio",
    "Explorer: Vasco da Gama",
    "Scientist: Einstein"];

  var details = {'Explorer':['person','How was the world when this person lived? - Antecedents','How did this person contribute to our world?','How is the world changed because of this person? - Postcedents'],
    'Invention':['invention','How did people do this job before the invention? - Antecedents','What is the function/benefit of the invention?','How do people do this job now? Is the invention still current? - Postcedents'],
    'Leader':['person','How was the world when this person lived? - Antecedents','How did this person contribute to our world?','How is the world changed because of this person? - Postcedents'],
    'Scientist':['person','How was the world when this person lived? - Antecedents','How did this person contribute to our world?','How is the world changed because of this person? - Postcedents'],
    'Writer':['person','How was the world when this person lived? - Antecedents','How did this person contribute to our world?','How is the world changed because of this person? - Postcedents'],
    'War':['historical conflict','What provocation/events led to the war? - Antecedents','Which countries were involved in the conflict?', 'Where did the war take place?', 'What years did the war cover?','How was the war resolved? Please include any treaty and immediate consequence. - Postcedents'],
    'historical event':['historical event','What key events caused this event to occur? - Antecedents','What are the details of the event?','What key events directly followed because of the event? - Postcedents']};


function historyProblem()
{  
  var index = Math.floor(Random()*historicalEvents.length);
  var theEvent = historicalEvents[index];
  var type="historical event";
  var location = theEvent.indexOf(":");
  var name = theEvent.substring(location+1);
  if(location>0)
  {
    type = theEvent.substring(0, location);
  }

  data = details[type];

  var temp = " Identify the "+data[0]+" "+name+" and write 3 descriptive paragraphs.<br><ul>";
  for(let i=1;i<data.length;i++)
  {
    temp += "<li>"+data[i]+"</li>";
  }

  return temp;
}